#!/usr/bin/env python3
import random
import time

#init cli arguments
import argparse
parser = argparse.ArgumentParser('broccoli')
parser.add_argument("-q","--quality", required=True,  help="Set the compression level (0-41)")
parser.add_argument("-f","--file", required=True, help="Set the file to compress")
args = parser.parse_args()

buff = "" #memory efficient buffer
try: #no exceptions, ever
  file = open(args.file, "r+") #inplace compression to ensure data integrity
  content = file.read()
  file.seek(0) #overwrite, so we're not making the file bigger
  for c in content:
    if (random.uniform(0,1) > (int(args.quality)/42)): #as long as a string isn't passed, everything things going to be okay
       buff = buff + c 
  file.write(buff)
  file.truncate() 
  file.close()
  time.sleep(0.5) #take a break, so we don't make brotli and gzip look too bad
except:
  print("Error.") #print industry standard, helpful error messsage
